### ISSUE TITLE
Substantial bug in Downdate

### ISSUE THREAD

**Issue by SnowmanTackler** [mp4096/cholesky-update#1]
In downdate you have:

```
for (i = (n - 1); i >= 0; --i)
{
   // Do Stuff
}
```
i is mwIndex, which on my machine is positive only.  So your loop termination check never fails.  i becomes a large positive number, then we try indexing arrays with it, a memory exception ensues.  I've changed to:

```
for (j = 0; j < n; ++j)
{        
   i = n - 1 - j;
   // Do Stuff
}
```

**Comment by SnowmanTackler** [comment]
Otherwise this looks great!  Thanks for posting.

**Comment by SnowmanTackler** [comment]
Did a little more digging:

> mwIndex is a type that represents index values, such as indices into arrays. Use this function for cross-platform flexibility. By default, mwIndex is equivalent to int in C. When using the mex -largeArrayDims switch, mwIndex is equivalent to size_t in C. In Fortran, mwIndex is similarly equivalent to INTEGER*4 or INTEGER*8, based on platform and compilation flags.

I'm using -largeArrayDims, which is why mwIndex is unsigned on my machine (and not on yours)

**Comment by mp4096** [comment]
Hi and thanks for this report :+1: 

Yeah, this is a typical C novice bug. TBH I wrote this program when I first started coding in C, nowadays I have much more respect (and fear) for C. I'll refactor this code till the end of the week. You're also very welcome to make a PR if you have some spare time.

**Comment by SnowmanTackler** [comment]
Done!
